export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SAVE_TITLE = 'SAVE_TITLE'